import com.itextpdf.text.Paragraph;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.io.FileOutputStream;
import com.itextpdf.text.Document;
import com.itextpdf.text.Image;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.File;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author LEGION
 */
public class PDf extends javax.swing.JFrame {
    
    String pathFile = "";
    public String userName = System.getProperty("user.name");
    public String directorioGlobalConfig = "C:\\Users\\" + userName+"\\Pictures\\Carpeta Exports\\";
    public void creardirectorio(){
        File directorio = new File("C:/Users/"+userName+"/Pictures/Carpeta Exports");
        if (!directorio.exists()) {
            if (directorio.mkdirs()) {
                System.out.println("Directorio creado");
            } else {
                System.out.println("Error al crear directorio");
            }
        }
    }
    
    private FileNameExtensionFilter filtro = new FileNameExtensionFilter("Archivos de imagen", "png");
    String rutaimagen;

    public PDf() {
        initComponents();
        rutaimagen = "";
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        txt_archivo = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Seleccionar Archivo...");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txt_archivo.setText("jLabel1");

        jButton2.setText("Generar PDF...");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txt_archivo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txt_archivo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(211, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        creardirectorio();
        //creamos un objeto de JFileChooser
        JFileChooser add = new JFileChooser();
        //del obj creado llamamos al metodo setFileFilter
        add.setFileFilter(filtro);
        //abriremos la ventana para escoger el archivo
        int option = add.showOpenDialog(this);
        //si hacemos clic en el boton selecionar 
        if (option == JFileChooser.APPROVE_OPTION) {
            //obtener el nombre del archivo seleccionado
            String fil = add.getSelectedFile().getPath(); // obtiene la url
            String file = add.getSelectedFile().toString(); // para mostrar la url en pantalla
            
            txt_archivo.setIcon(new ImageIcon(fil));
            
            pathFile = fil;
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        /*
        
        doc document = new Document();
        PdfWriter.getInstance(document, new FileOutputStream(dest));
        Rectangle one = new Rectangle(70, 140);
        Rectangle two = new Rectangle(700, 400);
        doc.setPageSize(one);
        doc.setMargins(2, 2, 2, 2);
        doc.open();
        Paragraph p = new Paragraph("Hi");
        doc.add(p);
        doc.setPageSize(two);
        doc.setMargins(20, 20, 20, 20);
        doc.newPage();
        doc.add(p);
        doc.close();
        /* fin*/
        
        //Document doc = new Document(); // por defecto esta en A4
        
        
        try {
            
            Document doc = new Document();
            PdfWriter.getInstance(doc, new FileOutputStream(directorioGlobalConfig+"test.pdf"));
            Rectangle one = new Rectangle(841.9f, 595.3f);
            Rectangle two = new Rectangle(595.3f, 841.9f);
            doc.setPageSize(one);
            doc.setMargins(2, 2, 2, 2);
            
            doc.open();
            
            //**
            Image img = Image.getInstance(pathFile);
            doc.add(img);
            //**
            Paragraph p = new Paragraph("Hi");
            doc.add(p);
            doc.setPageSize(two);
            doc.setMargins(20, 20, 20, 20);
            doc.newPage();
            doc.add(p);
            doc.close();
            /*
            PdfWriter.getInstance(doc, new FileOutputStream("test.pdf"));
            Rectangle one = new Rectangle(841.9f, 595.3f);
            Rectangle two = new Rectangle(595.3f, 841.9f);
            doc.setPageSize(one);
            
            doc.setPageSize(two);
            doc.setMargins(20, 20, 20, 20);
            doc.newPage();
            
            
            
            doc.open();
            
            Image img = Image.getInstance(pathFile);
            
            //img.scaleAbsoluteWidth(100f);
            
            doc.add(img);
            
            doc.close();
            */
            
        } catch (Exception ex) {
            System.out.println(ex.getMessage());
        }
        
        
        /*
        Graphics d = txt_archivo.getGraphics();

        try {
            FileOutputStream archivo = new FileOutputStream(d + ".pdf");
            Document doc = new Document();
            PdfWriter.getInstance(doc, archivo);
            doc.open();
            doc.add(new Paragraph(d));
            doc.close();
            System.out.println("documento creado con exito");

        } catch (Exception e) {
            System.out.println("Error" + e);
        }*/
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PDf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PDf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PDf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PDf.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PDf().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel txt_archivo;
    // End of variables declaration//GEN-END:variables
}
